aeternity/aepp-sdk-elixir

- .formatter.exs
- .travis.yml
> Travis CI integration

- apps/core/lib/account.ex
- apps/core/lib/client.ex
- apps/utils/lib/account.ex
- apps/utils/lib/keys.ex
- apps/utils/lib/transaction.ex
- apps/utils/test/test_utils.ex
- apps/utils/test/transaction_util_test.exs
> Implemented high-level Account module

- apps/core/lib/account.ex
- apps/core/lib/client.ex
- apps/utils/lib/transaction.ex
- apps/utils/test/transaction_util_test.exs
Resolves #39 . Should be merged before PR #40 
@d-velev @cheezus1  Please feel free to adjust contracts if there is a need for some changes.
> Added gas_price as part of the client

- apps/core/lib/contract.ex
- apps/core/test/core_contract_test.exs
> Automatically decode contract call return value

- apps/core/lib/client.ex
- apps/core/lib/name.ex
- apps/utils/lib/transaction.ex
> Fee calculation and documentation adjustments

- aeternity.yaml
- apps/core/lib/account.ex
- apps/core/lib/contract.ex
- apps/core/lib/name.ex
- apps/core/lib/oracle.ex
- apps/core/test/core_contract_test.exs
- apps/core/test/core_oracle_test.exs
- apps/utils/lib/governance.ex
- apps/utils/lib/transaction.ex
> Fixed fee calculation

- apps/core/lib/client.ex
- apps/core/lib/name.ex
- apps/core/test/naming_test.exs
- apps/utils/test/test_utils.ex
> Added tests for Naming system

- apps/core/lib/contract.ex
- apps/core/lib/name.ex
- apps/core/test/core_contract_test.exs
- apps/core/test/core_oracle_test.exs
- apps/utils/lib/governance.ex
- apps/utils/lib/serialization_utils.ex
- apps/utils/lib/transaction.ex
- apps/utils/test/transaction_util_test.exs
> Removed fee from tests

- README.md
- apps/core/test/core_naming_test.exs
- mix.exs
- mix.lock
> Check support for Fortuna release (v3.0.0) 

- lib/core/client.ex
- lib/core/name.ex
- lib/utils/encoding.ex
- lib/utils/hash.ex
- lib/utils/keys.ex
- lib/utils/transaction.ex
> Add missing docs to modules

- lib/core/chain.ex
- lib/core/contract.ex
- lib/core/name.ex
- lib/core/oracle.ex
- lib/utils/account.ex
- lib/utils/chain.ex
- lib/utils/encoding.ex
- lib/utils/keys.ex
- lib/utils/serialization.ex
- lib/utils/transaction.ex
> Documentation adjustment

- CHANGELOG.md
- mix.exs
> Added changelog.md file and modified mix.exs

- mix.exs
- test/core_chain_test.exs
- test/core_naming_test.exs
> Fix chain tests

- test/core_oracle_test.exs
resolves #91 
The only notable error that may occur, is highlighted in the issue. You can expand it further with more fault cases
> Fix Oracle tests

- README.md
- examples/usage.md
> Added example usage of elixir sdk 

- lib/core/channel.ex
- lib/utils/serialization.ex
> Proof-of-Inclusion serialization

- lib/core/listener/listener.ex
- lib/core/listener/peer_connection.ex
- test/core_listener_test.exs
closes #99 
Notifications for transactions now also include the transaction hashes
> Listener transaction confirmation service

- lib/core/channel.ex
- lib/utils/account.ex
- lib/utils/transaction.ex
- test/core_channel_test.exs
> State Channels (Transactions GA + GA post and Basic + GA post)

- lib/core/listener/listener.ex
- lib/core/listener/peer_connection.ex
> Fix listener messages duplication

- lib/core/listener/peer_connection.ex
closes #109 
Just to be on the safe side
> Ignore unknown peer messages

- .travis.yml
- README.md
> Upgrade to node v4.0.0

- lib/core/contract.ex
- lib/core/listener/listener.ex
- lib/core/listener/peer_connection.ex
- test/core_listener_test.exs
> Contract event listener

- lib/core/contract.ex
- lib/core/generalized_account.ex
- mix.exs
- mix.lock
- test/core_chain_test.exs
- test/core_channel_test.exs
- test/core_contract_test.exs
- test/core_generalized_account_test.exs
- test/core_listener_test.exs
- test/test_utils.ex
- test/transaction_util_test.exs
resolves #119 
Updated aesophia to v3.2.0
> Allow dry-running without a keypair

- lib/core/channel.ex
- lib/utils/serialization.ex
- test/core_channel_test.exs
resolves #104 
**NOTE:** `force_progress` is still not ready!
> Added more tests and examples to specific Channel transactions 

- .travis.yml
- README.md
- aeternity.yaml
> Updated java version and  aenode to v4.2.1

- examples/usage.md
> Updated example usage

- lib/core/account.ex
- lib/core/contract.ex
- lib/core/name.ex
- lib/core/oracle.ex
- lib/utils/transaction.ex
- test/core_naming_test.exs
- test/core_oracle_test.exs
> Fixed fee logic for all txs

- examples/usage.md
> Updated tag version in example usage

- .travis.yml
- README.md
- mix.lock
- test/utils_keys_test.exs
> Support Aeternity node v5.0.0

- .travis.yml
- README.md
- mix.lock
> Updated aeternity node to v5.0.2

- lib/utils/transaction.ex
> Increased await attempts

- README.md
- mix.exs
> Adjusted main documentation

- .travis.yml
- README.md
- mix.lock
> Updated aeternity node to v5.1.0

- .travis.yml
- README.md
- examples/usage.md
- lib/core/middleware.ex
- lib/utils/governance.ex
- mix.exs
> Adjusted Fate contract call gas price 

- .travis.yml
- Dockerfile
- README.md
- mix.exs
> Added dockerfile

- lib/core/name.ex
- lib/utils/transaction.ex
> Adjusted naming piping functionality

- lib/core/chain.ex
> Adjusted chain module

- .travis.yml
- README.md
- lib/core/contract.ex
- lib/utils/transaction.ex
- mix.lock
- test/core_chain_test.exs
- test/core_contract_test.exs
- test/core_generalized_account_test.exs
- test/core_listener_test.exs
- test/core_oracle_test.exs
- test/test_utils.ex
> Adjusted meta transaction fee calculation 

- lib/core/contract.ex
- lib/utils/transaction.ex
> Adjusted contract id for GA calculation

- README.md
- examples/usage.md
- mix.exs
> Update example usage

- lib/core/oracle.ex
- test/core_oracle_test.exs
> Adjusted oracle module to work correctly with all abi versions
